import Head from 'next/head';
import About from '../components/About';
import Banner from '../components/Banner';
import Contact from '../components/Contact';
import Faqc from '../components/Faqc';
import Features from '../components/Features';
import Footer from '../components/Footer';
import Howitworks from '../components/HowItWorks';
import SiteHeader from '../components/SiteHeader';
import Solutions from '../components/Solutions';
import WhyChooseUs from '../components/WhyChooseUs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader />
      <Banner />
      <Features />
      <About />
      <Solutions />
      <Howitworks />
      <WhyChooseUs />
      <Faqc />
      <Contact />
      <Footer />
    </div>
  );
}
