import axios from 'axios';
import Head from 'next/head';
import React from 'react';
import About from '../components/About';
import Banner from '../components/Banner';
import Contact from '../components/Contact';
import Faqc from '../components/Faqc';
import Features from '../components/Features';
import Howitworks from '../components/HowItWorks';
import Solutions from '../components/Solutions';
import Footer from '../components/ui/Footer';
import SiteHeader from '../components/ui/SiteHeader';
import WhyChooseUs from '../components/WhyChooseUs';

export default function Home({ mainMenu, footerMenu }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader mainMenu={mainMenu} />
      <Banner />
      <Features />
      <About />
      <Solutions />
      <Howitworks />
      <WhyChooseUs />
      <Faqc />
      <Contact />
      <Footer footerMenu={footerMenu} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const { req } = context;
  const mainMenu = await axios.get(`${req.headers.referer}/api/menu/main`);
  const footerMenu = await axios.get(`${req.headers.referer}/api/menu/footer`);
  return {
    props: {
      mainMenu: JSON.parse(mainMenu.data.param1),
      footerMenu: JSON.parse(footerMenu.data.param1)
    }
  };
}
