const fieldData = {
  mollie: {
    apiKey: true,
    secretKey: false,
    email: false,
    ex1: { status: false, label: 'N/A' },
    ex2: { status: false, label: 'N/A' },
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'SGD'],
  },
  coinbase: {
    apiKey: true,
    secretKey: false,
    email: false,
    ex1: { status: false, label: 'N/A' },
    ex2: { status: false, label: 'N/A' },
    supportedCurrencies: ['USD', 'EUR'],
  },
  coinpayments: {
    apiKey: true,
    secretKey: true,
    email: false,
    ex1: { status: false, label: 'N/A' },
    ex2: { status: false, label: 'N/A' },
    supportedCurrencies: ['BTC', 'ETH', 'USDC', 'XRP', 'USDT', 'SOL', 'BNB'],
  },
  coingate: {
    apiKey: true,
    secretKey: false,
    email: false,
    ex1: { status: true, label: 'Mode' },
    ex2: { status: false, label: 'N/A' },
    supportedCurrencies: ['BTC', 'ETH', 'XRP', 'BNB', 'USDT', 'USDC', 'SOL', 'ADA'],
  },
  paypal: {
    apiKey: true,
    secretKey: true,
    email: false,
    ex1: { status: true, label: 'Environment' },
    ex2: { status: false, label: 'N/A' },
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'SGD', 'JPY', 'INR'],
  },
  stripe: {
    apiKey: true,
    secretKey: true,
    email: false,
    ex1: { status: true, label: 'Signing Secret' },
    ex2: { status: false, label: 'N/A' },
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'CAD', 'SGD', 'JPY', 'NGN', 'INR'],
  },
  paystack: {
    apiKey: true,
    secretKey: false,
    email: false,
    ex1: { status: false, label: 'N/A' },
    ex2: { status: false, label: 'N/A' },
    supportedCurrencies: ['USD', 'NGN'],
  },
  voguepay: {
    apiKey: false,
    secretKey: false,
    email: false,
    ex1: { status: true, label: 'Merchant ID' },
    ex2: { status: false, label: 'N/A' },
    supportedCurrencies: ['USD', 'NGN', 'EUR', 'GBP', 'ZAR', 'JPY', 'INR', 'AUD'],
  },
  perfectmoney: {
    apiKey: false,
    secretKey: false,
    email: false,
    ex1: { status: true, label: 'USD Wallet' },
    ex2: { status: true, label: 'BTC Wallet' },
    supportedCurrencies: ['USD', 'BTC'],
  },
  paydunya: {
    apiKey: true,
    secretKey: true,
    email: false,
    ex1: { status: true, label: 'Master Key' },
    ex2: { status: true, label: 'Token' },
    supportedCurrencies: ['XOF'],
  },
  om: {
    apiKey: false,
    secretKey: false,
    email: false,
    ex1: { status: false, label: 'Username' },
    ex2: { status: false, label: 'Password' },
    supportedCurrencies: ['XOF'],
  },
  mtn: {
    apiKey: false,
    secretKey: false,
    email: false,
    ex1: { status: false, label: 'Username' },
    ex2: { status: false, label: 'Password' },
    supportedCurrencies: ['XOF'],
  },
  moov: {
    apiKey: false,
    secretKey: false,
    email: false,
    ex1: { status: false, label: 'Username' },
    ex2: { status: false, label: 'Password' },
    supportedCurrencies: ['XOF'],
  },
};

module.exports = fieldData;
